version: "3.7"
services:
  uisptools:
    image: "ghcr.io/andrewiski/uisptools:latest"
    ports:
      - "49443:49443"
      - "49080:49080"
    volumes:
      - /usr/src/uisptools/config:/usr/src/uisptools/config
      - /var/log:/usr/src/uisptools/logs
    container_name: uisptools
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "uisptools"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "U!spT00ls!"
      ME_CONFIG_MONGODB_URL: "mongodb://uisptools:U!spT00ls!@mongo:27017/"
    depends_on:
      - mongo
    networks:
    - express-mongo
    restart: always
  mongo:
    image: mongo
    container_name: uisptools_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "uisptools"
      MONGO_INITDB_ROOT_PASSWORD: "U!spT00ls!"
      MONGO_INITDB_DATABASE: "uisptools"
    volumes:
      - /usr/src/uisptools/data/mongodb:/data/db
      - ./mongodb/createDatabase.js:/docker-entrypoint-initdb.d/createDatabase.js:ro
    expose:
      - 27017
    restart: always
    networks:
    - express-mongo
networks:
  express-mongo:
